#!/bin/sh
# stripmb: Strip unwanted (not all) MusicBrainz metadata within $CWD.
#
# Copyright 2008 David Egan Evans
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented; you must
# not claim that you wrote the original software. If you use this
# software in a product, an acknowledgment in the product documentation
# would be appreciated but is not required.
#
# 2. Altered source versions must be plainly marked as such, and must 
# not be misrepresented as being the original software.
#
# 3. This notice may not be removed or altered from any source distribution.
#
# Dependencies: flac
stripmb() {
	if ls *.flac 2>&1 >/dev/null
	then
		metaflac --remove-tag=Musicbrainz_albumid *.flac
		metaflac --remove-tag=Musicbrainz_albumartistid *.flac
		metaflac --remove-tag=Musicbrainz_artistid *.flac
		metaflac --remove-tag=Musicbrainz_discid *.flac
		metaflac --remove-tag=Musicbrainz_trackid *.flac
		metaflac --remove-tag=Musicbrainz_sortname *.flac
		metaflac --remove-tag=Artistsort *.flac
		metaflac --remove-tag=Discid *.flac
	else echo "No FLAC files found in $CWD" 1>&2; exit 2
	fi
}

usage() {
	echo "Usage: stripmb" 1>&2
	echo 1>&2
}

if test $# -ge 1; then
	usage
else
	if test $# -lt 1
	then stripmb
	fi
fi
